name: CI

on:
  push:
    branches:
      - main
    paths:
      - '**'
      - '!**.md'
      - '!.github/**'
      - '.github/scripts/**'
      - '.github/workflows/build_push.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CI_CHUNK_SIZE: 65

permissions:
  contents: write

jobs:
  prepare:
    name: Prepare job
    runs-on: ubuntu-latest
    outputs:
      individualMatrix: ${{ steps.generate-matrices.outputs.individualMatrix }}
      multisrcMatrix: ${{ steps.generate-matrices.outputs.multisrcMatrix }}
      delete: ${{ steps.generate-matrices.outputs.delete }}
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Get list of changed files and generate matrices
        id: generate-matrices
        run: |
          python .github/scripts/generate-build-matrices.py "${{ github.event.before || 'HEAD~1' }}"

  build:
    name: Build extensions
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.prepare.outputs.individualMatrix) }}
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Prepare signing key
        run: |
          echo "${{ secrets.SIGNING_KEY }}" | base64 -d > signingkey.jks

      - name: Build extensions
        env:
          ALIAS: ${{ secrets.ALIAS }}
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          ./gradlew ${{ matrix.projects }}

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: "apks-${{ matrix.chunk }}"
          path: "**/*.apk"
          retention-days: 1

  publish:
    name: Publish extension repo
    needs: [prepare, build]
    runs-on: ubuntu-latest
    steps:
      - name: Download APK artifacts
        uses: actions/download-artifact@v4
        with:
          path: ~/apk-artifacts
          pattern: "apks-*"
          merge-multiple: true

      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          path: main

      - name: Checkout repo branch
        uses: actions/checkout@v4
        with:
          ref: repo
          path: repo

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Publish and deploy repo
        env:
          DELETE: ${{ needs.prepare.outputs.delete }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd repo
          if [ ! -f index.json ]; then
            echo "[]" > index.json
          fi
          pip install protobuf
          python -u ../main/.github/scripts/publish-repo.py "$DELETE" "$GITHUB_SHA"
          cp index.json index.min.json
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Update extensions repo"
            git push origin repo
          else
            echo "No changes to commit"
          fi
