name: Build and push

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    name: Build ScanManga
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Generate local keystore
        run: |
          keytool -genkeypair -v \
            -keystore signingkey.jks \
            -alias androiddebugkey \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass android \
            -keypass android \
            -dname "CN=Android,OU=Android,O=Android,L=Android,ST=Android,C=US"

      - name: Compile APK
        env:
          KEY_ALIAS: androiddebugkey
          KEY_PASSWORD: android
        run: |
          ./gradlew :src:fr:scanmanga:assembleRelease --stacktrace

      - name: Archive compiled APK
        uses: actions/upload-artifact@v4
        with:
          name: ScanManga-APK
          path: "**/*.apk"
