name: Generate Keystore
on: workflow_dispatch
jobs:
  gen:
    runs-on: ubuntu-latest
    steps:
      - run: |
          keytool -genkeypair -v -keystore release.jks -alias mihon -keyalg RSA -keysize 2048 -validity 10000 -storepass MonMotDePasse123 -keypass MonMotDePasse123 -dname "CN=Mihon, OU=Dev, O=Self, L=Paris, S=IDF, C=FR"
          base64 -w 0 release.jks > key_base64.txt
          cat key_base64.txt
